---
- name: Prepare Server
  hosts: main
  gather_facts: true
  roles:
    - { role: prepare, become: true }
    - { role: proxy, become: true }
    - { role: certificates, become: true }

- name: Setup Docker registry
  hosts: main
  gather_facts: true
  roles:
    - { role: docker, become: true }
    - { role: registry, become: true }

- name: Setup Wordpress
  hosts: main
  gather_facts: true
  roles:
    - { role: wordpress, become: true }
