---
- name: Removing_Unofficial_Packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    force: true
    force_apt_get: true
    purge: true
    clean: true
    lock_timeout: 60
  loop: "{{ docker_obselete_packages }}"

- name: Updating_APT_Source_List
  become: true
  ansible.builtin.apt:
    force: true
    force_apt_get: true
    update_cache: true
    update_cache_retries: 3
    cache_valid_time: 86400
    upgrade: safe
    autoclean: true
    autoremove: true
    lock_timeout: 60
