---
- name: Create_letsencrypt_live_Dir
  become: true
  check_mode: false
  ansible.builtin.file:
    path: /etc/letsencrypt/live
    mode: "0644"
    owner: root
    group: root
    state: directory

- name: Create_letsencrypt_live_Dir
  become: true
  check_mode: false
  ansible.builtin.file:
    path: /etc/letsencrypt/live/wp.mahmoudisari.ir
    mode: "0644"
    owner: root
    group: root
    state: directory

- name: Modifying_letsencrypt_privkey
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 03-privkey.pem.j2
    dest: /etc/letsencrypt/live/wp.mahmoudisari.ir/privkey.pem
    mode: "0644"
    owner: root
    group: root
    force: true

- name: Modifying_letsencrypt_fullchain
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 03-fullchain.pem.j2
    dest: /etc/letsencrypt/live/wp.mahmoudisari.ir/fullchain.pem
    mode: "0644"
    owner: root
    group: root
    force: true

- name: Removing_Unofficial_Packages
  become: true
  check_mode: false
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    force: true
    force_apt_get: true
    purge: true
    clean: true
    lock_timeout: 60
  loop: "{{ docker_obselete_packages }}"

- name: Updating_APT_Source_List
  become: true
  check_mode: false
  ansible.builtin.apt:
    force: true
    force_apt_get: true
    update_cache: true
    update_cache_retries: 3
    cache_valid_time: 86400
    upgrade: safe
    autoclean: true
    autoremove: true
    lock_timeout: 60

- name: Creating_APT_Keyrings_Directory
  become: true
  check_mode: false
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Kill_All_Process_On_Port_1081
  become: true
  check_mode: false
  ansible.builtin.command:
    cmd: "/bin/bash -c 'kill -9 $(lsof -i :1081)'"
  changed_when: false
  failed_when: false

- name: Executing_VPN_Files
  become: true
  check_mode: false
  ansible.builtin.command:
    cmd: "/bin/bash -c '/home/ubuntu/Xray-linux-64/vpn > /home/ubuntu/log.txt 2>&1 &'"
  changed_when: false
  failed_when: false
  async: 3600
  poll: 0

- name: Pause_Execution_Of_Task_For_VPN
  become: true
  check_mode: false
  ansible.builtin.pause:
    seconds: 30
    prompt: "Please Wait ..."
  failed_when: false

- name: Check_Port_1081_Second
  become: true
  check_mode: false
  ansible.builtin.command:
    cmd: "/bin/bash -c 'netstat -tuln | grep :1081'"
  changed_when: false
  failed_when: false

- name: Obtaining_Docker_GPG_Key
  become: true
  check_mode: false
  ansible.builtin.uri:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0755"
    owner: root
    group: root
    method: GET
    return_content: true
    timeout: 60
    force: true
    creates: /etc/apt/keyrings/docker.asc
  environment: "{{ proxy_env }}"

- name: Adding_Docker_Source_List
  become: true
  check_mode: false
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] \
      https://download.docker.com/linux/ubuntu jammy stable"
    state: present
    update_cache: true
    update_cache_retries: 3
  failed_when: false
  environment: "{{ proxy_env }}"

- name: Installing_Docker_Latest_Packages
  become: true
  check_mode: false
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    update_cache_retries: 3
    lock_timeout: 60
    force_apt_get: true
    autoclean: true
    autoremove: true
    force: true
  loop: "{{ docker_latest_packages }}"
  environment: "{{ proxy_env }}"
