- name: Creating_Docker_Daemon_Directory_etcdocker
  become: true
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Creating_Docker_Daemon_Directory_etcsystemd
  become: true
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'
