- name: Creating_Docker_Daemon_Directory_etcdocker
  become: true
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Creating_Docker_Daemon_Directory_etcsystemd
  become: true
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Modifying_Docker_Daemon_etcsystemd
  become: true
  ansible.builtin.template:
    src: 02-systemd_docker_daemon.conf.j2
    dest: /etc/systemd/system/docker.service.d
    backup: true
    owner: root
    group: root
    mode: '0644'
    force: true
  notify:
    - Restart_Docker
