---
- name: Creating_Registry_Userfile_Directory
  become: true
  ansible.builtin.file:
    path: /etc/nginx/auth
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Creating_Nginx_Data_Directory
  become: true
  ansible.builtin.file:
    path: /etc/nginx/data
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Updating_APT_Source_List_For_Htpasswd
  become: true
  ansible.builtin.apt:
    update_cache: true
    update_cache_retries: 3
    cache_valid_time: 86400
    autoclean: true
    autoremove: true
    force_apt_get: true
    force: true
    upgrade: safe
    lock_timeout: 60

- name: Installing_Apache2_Utils-Htpasswd
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    force_apt_get: true
    force: true
    lock_timeout: 60
  loop:
    - apache2-utils
    - python3-passlib
    - certbot

- name: Creating_Registry_Userfile_Htpasswd
  become: true
  community.general.htpasswd:
    path: /etc/nginx/auth/nginx.htpasswd
    owner: root
    group: root
    mode: '0755'
    state: present
    name: parsa
    password: parsa

- name: Obtaining_SSL_Certificate
  become: true
  ansible.builtin.command:
    cmd: "certbot certonly \
      --standalone --noninteractive  \
      --agree-tos -d wordpress.mahmoudisari.ir -d registry.mahmoudisari.ir \
      --preferred-challenges http-01 --email iamapmas1382@outlook.com"
  changed_when: false

- name: Creating_Docker_Compose_Directory
  become: true
  ansible.builtin.file:
    path: /home/ubuntu/project
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Modifying_Docker_Compose_File
  become: true
  ansible.builtin.template:
    src: 03-docker-compose.yml.j2
    dest: /home/ubuntu/project/docker-compose.yml
    backup: true
    owner: root
    group: root
    mode: '0755'
    force: true

- name: Test_Docker_Compose_Configuration_File
  become: true
  ansible.builtin.command:
    cmd: "/bin/bash -c 'cd /home/ubuntu/project && docker compose config'"
  changed_when: false

- name: Docker_Compose_Down_Prepairation
  become: true
  community.docker.docker_compose_v2:
    state: absent
    project_src: /home/ubuntu/project
    remove_volumes: true
    remove_orphans: true

- name: Docker_Compose_Up_Execution
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/ubuntu/project
    state: present
    recreate: always
    dependencies: true
  environment: "{{ proxy_env }}"
