---
- name: Creating_Registry_Userfile_Directory
  become: true
  check_mode: false
  ansible.builtin.file:
    path: /etc/nginx/auth
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Creating_Nginx_Data_Directory
  become: true
  check_mode: false
  ansible.builtin.file:
    path: /etc/nginx/data
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Creating_Registry_Userfile_Htpasswd
  become: true
  check_mode: true
  community.general.htpasswd:
    path: /etc/nginx/auth/nginx.htpasswd
    owner: root
    group: root
    mode: '0755'
    state: present
    name: parsa
    password: parsa

- name: Creating_Docker_Compose_Directory
  become: true
  check_mode: false
  ansible.builtin.file:
    path: /home/ubuntu/project
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Modifying_Docker_Compose_File
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 03-docker-compose.yml.j2
    dest: /home/ubuntu/project/docker-compose.yml
    backup: true
    owner: root
    group: root
    mode: '0755'
    force: true

- name: Creating_Registry_Compose_Directory
  become: true
  check_mode: false
  ansible.builtin.file:
    path: /home/ubuntu/registry
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Modifying_Registry_Compose_File
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 03-newregistry-compose.yml.j2
    dest: /home/ubuntu/registry/docker-compose.yml
    backup: true
    owner: root
    group: root
    mode: '0755'
    force: true

- name: Test_Docker_Compose_Configuration_File
  become: true
  check_mode: false
  ansible.builtin.command:
    cmd: "/bin/bash -c 'cd /home/ubuntu/project && docker compose config'"
  changed_when: false
  failed_when: false

- name: Test_Registry_Compose_Configuration_File
  become: true
  check_mode: false
  ansible.builtin.command:
    cmd: "/bin/bash -c 'cd /home/ubuntu/registry && docker compose config'"
  changed_when: false
  failed_when: false

- name: Registry_Compose_Down_Prepairation
  become: true
  check_mode: false
  community.docker.docker_compose_v2:
    state: absent
    project_src: /home/ubuntu/registry
    remove_volumes: true
    remove_orphans: true
  environment: "{{ proxy_env }}"
  failed_when: false

- name: Docker_Compose_Down_Prepairation
  become: true
  check_mode: false
  community.docker.docker_compose_v2:
    state: absent
    project_src: /home/ubuntu/project
    remove_volumes: true
    remove_orphans: true
  environment: "{{ proxy_env }}"
  failed_when: false

- name: Docker_Compose_Up_Execution
  check_mode: false
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/ubuntu/registry
    state: present
    recreate: auto
    dependencies: true
  environment: "{{ proxy_env }}"

- name: Pause_Execution_Of_Task_Before_DockerLogin
  become: true
  check_mode: false
  ansible.builtin.pause:
    seconds: 30
    prompt: "Please Wait ..."
  failed_when: false

- name: Docker_Registry_Login
  become: true
  check_mode: false
  community.docker.docker_login:
    registry_url: https://registry.mahmoudisari.ir
    username: parsa
    password: parsa
    state: present
    timeout: 60

- name: Moving_Wordpress_Nginx_Config_To_Confd
  become: true
  check_mode: false
  ansible.builtin.command:
    cmd: "/bin/bash -c 'mv /home/ubuntu/project/wordpress_nginx.conf \
     /etc/nginx/conf.d/wordpress_nginx.conf'"
  changed_when: false

- name: Restarting_Nginx_Container
  become: true
  check_mode: false
  community.docker.docker_container:
    name: nginx
    state: started
    restart: true

- name: Docker_Compose_Up_Execution
  check_mode: false
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/ubuntu/project
    state: present
    recreate: auto
    dependencies: true
  environment: "{{ proxy_env }}"
