---
- name: Transfer arvancloud_api.py
  become: true
  check_mode: false
  ansible.builtin.template:
    src: arvancloud_api.py.j2
    dest: /home/ubuntu/arvancloud_api.py
    owner: root
    group: root
    mode: "0644"

- name: Execute arvancloud_api.py
  become: true
  check_mode: false
  ansible.builtin.command:
    cmd: python3 /home/ubuntu/arvancloud_api.py
  changed_when: false

- name: Create certificates directory
  become: true
  check_mode: false
  ansible.builtin.file:
    path: /etc/certs/{{ root_domain }}
    state: directory
    owner: root
    group: root
    mode: "0755"
    recurse: true
  tags: ssl

- name: Add private key
  become: true
  ansible.builtin.template:
    src: privkey.pem.j2
    dest: "/etc/certs/{{ root_domain }}/privkey.pem"
    owner: root
    group: root
    mode: "0644"
  tags: ssl

- name: Add full-chain certificate
  become: true
  check_mode: false
  ansible.builtin.copy:
    src: fullchain.pem
    dest: "/etc/certs/{{ root_domain }}/fullchain.pem"
    owner: root
    group: root
    mode: "0644"
  tags: ssl
