---
- name: Execute arvancloud_api.py
  become: false
  check_mode: false
  ansible.builtin.command:
    chdir: "{{ role_path }}"
    cmd: "/bin/bash -c 'python3 \
      files/arvancloud_api.py \
      --wpdomain {{ wordpress.subdomain }} --regdomain {{ registry.subdomain }} \
      --rootdomain {{ root_domain }} --apikey {{ arvancloud_api.apikey }} \
      --ansiblehost {{ ansible_host }}'"
  changed_when: false
  delegate_to: localhost

- name: Create certificates directory
  become: true
  check_mode: false
  ansible.builtin.file:
    path: /etc/certs/{{ root_domain }}
    state: directory
    owner: root
    group: root
    mode: "0755"
    recurse: true
  tags: ssl

- name: Add private key
  become: true
  ansible.builtin.template:
    src: privkey.pem.j2
    dest: "/etc/certs/{{ root_domain }}/privkey.pem"
    owner: root
    group: root
    mode: "0644"
  tags: ssl

- name: Add full-chain certificate
  become: true
  check_mode: false
  ansible.builtin.copy:
    src: fullchain.pem
    dest: "/etc/certs/{{ root_domain }}/fullchain.pem"
    owner: root
    group: root
    mode: "0644"
  tags: ssl
