---
- name: Updating_APT_Source_List
  become: true
  ansible.builtin.apt:
    force: true
    force_apt_get: true
    update_cache: true
    update_cache_retries: 3
    cache_valid_time: 86400
    upgrade: safe
    autoclean: true
    autoremove: true
    lock_timeout: 60

- name: Installing_Hardening_Required_Packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    update_cache_retries: 3
    lock_timeout: 60
    force_apt_get: true
    autoclean: true
    autoremove: true
    force: true
  loop: "{{ hardening_required_packages }}"
  environment: "{{ proxy_env }}"
