---
- name: Updating_APT_Source_List
  become: true
  check_mode: false
  ansible.builtin.apt:
    force: true
    force_apt_get: true
    update_cache: true
    update_cache_retries: 3
    cache_valid_time: 86400
    upgrade: safe
    autoclean: true
    autoremove: true
    lock_timeout: 60

- name: Downloading_Xray_Linux_64bit_Release
  become: true
  check_mode: false
  ansible.builtin.uri:
    url: https://github.com/XTLS/Xray-core/releases/download/v1.8.9/Xray-linux-64.zip
    owner: ubuntu
    group: ubuntu
    mode: "0755"
    dest: /home/ubuntu
    method: GET
    force: true

- name: Creating_Xray_Directory
  become: true
  check_mode: false
  ansible.builtin.file:
    path: /home/ubuntu/Xray-linux-64
    owner: root
    group: root
    mode: "0755"
    recurse: true
    state: directory

- name: Installing_Hardening_Required_Packages
  become: true
  check_mode: false
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    update_cache_retries: 3
    lock_timeout: 60
    force_apt_get: true
    autoclean: true
    autoremove: true
    force: true
  loop: "{{ hardening_required_packages }}"

- name: Extracting_Xray_Linux_64Bit_Release
  become: true
  check_mode: false
  ansible.builtin.unarchive:
    src: /home/ubuntu/Xray-linux-64.zip
    dest: /home/ubuntu/Xray-linux-64
    remote_src: true
    mode: "0755"
    owner: root
    group: root

- name: Setting_Hostname_Using_Ansible
  become: true
  check_mode: false
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Modifying_etc_hosts
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 01-hostnames.j2
    dest: /etc/hosts
    backup: true
    owner: root
    group: root
    mode: "0755"
    force: true

- name: Removing_TMP_Directory_From_Fstab
  become: true
  check_mode: false
  ansible.posix.mount:
    path: /tmp
    state: absent

- name: Removing_Floppy_From_Fstab
  become: true
  check_mode: false
  ansible.builtin.lineinfile:
    path: /etc/fstab
    owner: root
    group: root
    mode: "0755"
    state: absent
    regexp: '^(.*)floppy(.*)$'

- name: Modifying_Limits_Conf
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 01-limits.conf.j2
    dest: /etc/security/limits.conf
    backup: true
    owner: root
    group: root
    mode: "0755"
    force: true

- name: Modifying_Coredump_Conf
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 01-coredump.conf.j2
    dest: /etc/systemd/coredump.conf
    backup: true
    owner: root
    group: root
    mode: "0755"
    force: true

- name: Modifying_Systemd_Resolved_Conf
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 01-resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    backup: true
    owner: root
    group: root
    mode: "0755"
    force: true
  notify:
    - Reload_Systemd

- name: Modifying_Etc_Resolv_Conf
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 01-resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: "0755"
    force: true
    backup: true
    follow: true

- name: Modifying_Hosts_Allow_Conf
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 01-hosts.allow.j2
    dest: /etc/hosts.allow
    backup: true
    owner: root
    group: root
    mode: "0755"
    force: true

- name: Modifying_Hosts_Deny_Conf
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 01-hosts.deny.j2
    dest: /etc/hosts.deny
    backup: true
    owner: root
    group: root
    mode: "0755"
    force: true
