---
- name: Stop_And_Disable_UFW
  become: true
  ansible.builtin.service:
    name: ufw
    state: stopped
    enabled: false
  failed_when: false

- name: Stop_And_Disable_Postfix
  become: true
  ansible.builtin.service:
    name: postfix
    state: stopped
    enabled: false
  failed_when: false
