---
- name: Kill_All_Process_On_Port_1081
  become: true
  check_mode: false
  ansible.builtin.command:
    cmd: "/bin/bash -c 'kill -9 $(lsof -i :1081)'"
  changed_when: false
  failed_when: false

- name: Executing_VPN_Files
  become: true
  check_mode: false
  ansible.builtin.command:
    cmd: "/bin/bash -c '/home/ubuntu/Xray-linux-64/vpn > /home/ubuntu/log.txt 2>&1 &'"
  changed_when: false
  failed_when: false
  async: 3600
  poll: 0

- name: Pause_Execution_Of_Task_For_VPN
  become: true
  check_mode: false
  ansible.builtin.pause:
    seconds: 30
    prompt: "Please Wait ..."
  failed_when: false

- name: Check_Port_1081
  become: true
  check_mode: false
  ansible.builtin.command:
    cmd: "/bin/bash -c 'netstat -tuln | grep :1081'"
  changed_when: false
  failed_when: false

- name: Stop_And_Disable_UFW
  become: true
  check_mode: false
  ansible.builtin.service:
    name: ufw
    state: stopped
    enabled: false
  failed_when: false

- name: Stop_And_Disable_Postfix
  become: true
  check_mode: false
  ansible.builtin.service:
    name: postfix
    state: stopped
    enabled: false
  failed_when: false

- name: Set_Timezone_To_Asia/Tehran
  become: true
  community.general.timezone:
    name: Asia/Tehran
  notify: Restart_NTP

- name: Set_Timeout_Configurations
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 02-timeout.j2
    dest: /etc/profile.d/timeout-settings.sh
    owner: root
    group: root
    mode: "0755"
    backup: true
    force: true

- name: Copying_SSH_Banner_File
  become: true
  check_mode: false
  ansible.builtin.copy:
    src: ssh_banner
    dest: /etc/issue
    owner: root
    group: root
    mode: "0755"
    force: true
    backup: true
  failed_when: false

- name: Making_SSHD_configuration_file
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 02-sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0755"
    backup: true
    force: true
  notify: Restart_SSH

- name: Making_Iptables_Configuration_File
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 02-iptables.j2
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: "0755"
    backup: true
    force: true

- name: Restoring_Iptables_State_From_File
  become: true
  check_mode: true
  community.general.iptables_state:
    path: /etc/iptables/rules.v4
    state: restored
    noflush: true
  notify: Restart_Iptables

