---
- name: Stop_And_Disable_UFW
  become: true
  ansible.builtin.service:
    name: ufw
    state: stopped
    enabled: false
  failed_when: false

- name: Stop_And_Disable_Postfix
  become: true
  ansible.builtin.service:
    name: postfix
    state: stopped
    enabled: false
  failed_when: false

- name: Set_Timezone_To_Asia/Tehran
  become: true
  community.general.timezone:
    name: Asia/Tehran
  notify: Restart_NTP

- name: Set_Timeout_Configurations
  become: true
  ansible.builtin.template:
    src: 02-timout.j2
    dest: /etc/profile.d/timeout-settings.sh
    owner: root
    group: root
    mode: "0755"
    backup: true
    force: true

- name: Copying_SSH_Banner_File
  become: true
  ansible.builtin.file:
    src: 02-ssh_banner
    dest: /etc/issue
    owner: root
    group: root
    mode: "0755"
    force: true

- name: Making_SSHD_configuration_file
  become: true
  ansible.builtin.template:
    src: 02-sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0755"
    backup: true
    force: true
  notify: Restart_SSH

- name: Making_Iptables_Configuration_File
  become: true
  ansible.builtin.template:
    src: 02-iptables.j2
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: "0755"
    backup: true
    force: true

- name: Restoring_Iptables_State_From_File
  become: true
  community.general.iptables_state:
    path: /etc/iptables/rules.v4
    state: restored
    ip_version: ipv4
    noflush: true
  notify: Restart_Iptables
