---
- name: Set_Debian_audit_grub_cmdline
  become: true
  ansible.builtin.lineinfile:
    line: 'GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX audit=1 audit_backlog_limit=8192'
    dest: /etc/default/grub.d/99-hardening-audit.cfg
    state: present
    create: true
    mode: "0755"
    owner: root
    group: root

- name: Modifying_Auditd_Conf_File
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 03-auditd.conf.j2
    dest: /etc/audit/auditd.conf
    backup: true
    owner: root
    group: root
    mode: "0755"
    force: true


- name: Modifying_Auditd_Rules_File
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 03-hardening.rules.j2
    dest: /etc/audit/rules.d/hardening.rules
    backup: true
    owner: root
    group: root
    mode: "0755"
    force: true
  notify:
    - Generate_Auditd
    - Restart_Auditd

- name: Modifying_Jounald_Conf_File
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 03-jounald.conf.j2
    dest: /etc/systemd/journald.conf
    backup: true
    owner: root
    group: root
    mode: "0755"
    force: true

- name: Modifying_Logrotate_Conf_File
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 03-logrotate.conf.j2
    dest: /etc/logrotate.conf
    backup: true
    owner: root
    group: root
    mode: "0755"
    force: true

- name: Cron.daily_logrotate
  become: true
  ansible.builtin.lineinfile:
    line: "/usr/sbin/logrotate /etc/logrotate.conf"
    dest: /etc/cron.daily/logrotate
    mode: "0750"
    state: present
    create: true

- name: Modifying_rsyslog_Conf_File
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 03-rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    backup: true
    owner: root
    group: root
    mode: "0640"
    force: true
