---
- name: Setting_Grub_Audit_Option
  become: true
  check_mode: false
  ansible.builtin.lineinfile:
    line: 'GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX audit=1 audit_backlog_limit=8192"'
    dest: /etc/default/grub.d/99-hardening-audit.cfg
    state: present
    create: true
    owner: "{{ user_groups.elevated_user }}"
    group: "{{ user_groups.elevated_user }}"
    mode: "{{ file_permissions.soft_nonexec }}"

- name: Transferring_Auditd_Conf_File
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 03-auditd.conf.j2
    dest: /etc/audit/auditd.conf
    owner: "{{ user_groups.elevated_user }}"
    group: "{{ user_groups.elevated_user }}"
    mode: "{{ file_permissions.soft_nonexec }}"

- name: Transferring_Auditd_Rules_File
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 03-hardening.rules.j2
    dest: /etc/audit/rules.d/hardening.rules
    owner: "{{ user_groups.elevated_user }}"
    group: "{{ user_groups.elevated_user }}"
    mode: "{{ file_permissions.soft_nonexec }}"
  notify:
    - Generate_Auditd

- name: Transferring_Jounald_Conf_File
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 03-journald.conf.j2
    dest: /etc/systemd/journald.conf
    owner: "{{ user_groups.elevated_user }}"
    group: "{{ user_groups.elevated_user }}"
    mode: "{{ file_permissions.soft_nonexec }}"

- name: Transferring_Logrotate_Conf_File
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 03-logrotate.conf.j2
    dest: /etc/logrotate.conf
    owner: "{{ user_groups.elevated_user }}"
    group: "{{ user_groups.elevated_user }}"
    mode: "{{ file_permissions.soft_nonexec }}"

- name: Setting_Cron.daily_logrotate_NewJob
  become: true
  check_mode: false
  ansible.builtin.lineinfile:
    line: "/usr/sbin/logrotate /etc/logrotate.conf"
    dest: /etc/cron.daily/logrotate
    state: present
    create: true
    owner: "{{ user_groups.elevated_user }}"
    group: "{{ user_groups.elevated_user }}"
    mode: "{{ file_permissions.soft_nonexec }}"

- name: Transferring_Rsyslog_Conf_File
  become: true
  check_mode: false
  ansible.builtin.template:
    src: 03-rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    owner: "{{ user_groups.elevated_user }}"
    group: "{{ user_groups.elevated_user }}"
    mode: "{{ file_permissions.soft_nonexec }}"
