---
- name: 01-Hardware_Related.yaml
  become: true
  ansible.builtin.import_tasks:
    file: 01-hardware_related.yaml
  tags: 01-hardware_related.yaml

- name: 02-Network_Related.yaml
  become: true
  ansible.builtin.import_tasks:
    file: 02-network_related.yaml
  tags: 02-network_related.yaml
